### Libraries USed Tensorflow> 2.0  and keras


In [1]:
##tensorflow >2.0
# first you have tensorflow background greater than 2..
from tensorflow.keras.preprocessing.text import one_hot # here we implement one_hot.. what the use of it, for this refer to copy notes

In [2]:
# here we have sentences where we perform some one_hot and embedding
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
sent # check it out

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:

### Vocabulary size
voc_size=10000
# its first step declare vocabulory, my vocab is 10000


#One Hot Representation


In [30]:
# so here we convert our sentence into one-hot representations...
onehot_repr=[]
for words in sent: # 
    print(words) 
    
    onehot_repr.append(one_hot(words,voc_size)) 
# its function that convert words into one-hot 
# here two parameter 1st is words which you want to convert into one-hot and another is voc_size 
# so after apply this one index no assign to our word.
# so its provide index no  to the word from our dictionary..
print(onehot_repr)


the glass of milk
the glass of juice
the cup of tea
I am a good boy
I am a good developer
understand the meaning of words
your videos are good
[[8041, 8904, 8698, 8958], [8041, 8904, 8698, 927], [8041, 7524, 8698, 6981], [5356, 5445, 5653, 3728, 5903], [5356, 5445, 5653, 3728, 9926], [8448, 8041, 5747, 8698, 8944], [5258, 8036, 601, 3728]]



# Word Embedding Represntation 

In [31]:
from tensorflow.keras.layers import Embedding # import embedding layer , its convert one-hot representaation into embedding vectors.
from tensorflow.keras.preprocessing.sequence import pad_sequences # import pad_sequence 
# why its very very important ,whenever you pass the sentences to the embedding layer, all the sentences should have the same no.of words,
#becoz its help to create very good embedding matrix.so for do same size sentence with use pad sequences
from tensorflow.keras.models import Sequential # its for init the sequential model ,here we use sequential model in order to create with repecting the embedding layer to create

In [32]:
import numpy as np


In [35]:
sent_length=8
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
# in pad_sequence 1st parameter is my one_hot representation sentence ,2nd is padding ='pre ', it mean o put in before the indexs
# 3rd is maxlen its mean total size of one-hot representation after performing padding
# for more go in my  google colab accound and check NLP python file of tokenizations
# if i dont pass 3rd parameter it will take by default size , by defualt size is larger sentece size..
print(embedded_docs)

[[   0    0    0    0 8041 8904 8698 8958]
 [   0    0    0    0 8041 8904 8698  927]
 [   0    0    0    0 8041 7524 8698 6981]
 [   0    0    0 5356 5445 5653 3728 5903]
 [   0    0    0 5356 5445 5653 3728 9926]
 [   0    0    0 8448 8041 5747 8698 8944]
 [   0    0    0    0 5258 8036  601 3728]]


In [16]:
dim=10
# its dimensional of embedding
# its feature , and one words convert into 10 vector size.
# to understand this refer to copy


In [36]:
model=Sequential() # here init the deep learning sequential model
model.add(Embedding(voc_size,10,input_length=sent_length)) #here i add embedding layer , my first layer of ANN is embedding laayer.
# 1st parameter is vocabulory size , 2nd parameter is dimesional , 3rd parameter is sentence length, so what is our each and every sentence lenght is 8
model.compile('adam','mse') # its compilee with adam optimizer and performing matrix is mean square error

In [37]:
model.summary()
# its my model.summmery

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_1 (Embedding)      (None, 8, 10)             100000    
Total params: 100,000
Trainable params: 100,000
Non-trainable params: 0
_________________________________________________________________


In [39]:
print(model.predict(embedded_docs))
# now here in order to see, how my words actually converted
# suppose we want to convert this 0    0    0    0 8041 8904 8698 8958 words convert into feature vector, for this we have to do 
# model.predict(here we give our index sentences)

[[[-0.03791308  0.02003479 -0.03470116 -0.02139171 -0.02203513
   -0.01278513 -0.00932705  0.01903306 -0.03308139  0.02439653]
  [-0.03791308  0.02003479 -0.03470116 -0.02139171 -0.02203513
   -0.01278513 -0.00932705  0.01903306 -0.03308139  0.02439653]
  [-0.03791308  0.02003479 -0.03470116 -0.02139171 -0.02203513
   -0.01278513 -0.00932705  0.01903306 -0.03308139  0.02439653]
  [-0.03791308  0.02003479 -0.03470116 -0.02139171 -0.02203513
   -0.01278513 -0.00932705  0.01903306 -0.03308139  0.02439653]
  [-0.02565583  0.00791759 -0.02996886  0.03961018 -0.01456248
   -0.04630274 -0.02392167  0.04627511 -0.01218774  0.03797766]
  [-0.02791396 -0.01811381  0.04219855 -0.01401313  0.01106535
    0.04672335 -0.04907656  0.02396217 -0.01073527 -0.01459684]
  [-0.01583047 -0.02237868 -0.00142431  0.04683676 -0.0438031
    0.02135683 -0.00830128  0.03181615 -0.00306803 -0.01186572]
  [-0.00576218  0.02043792  0.02381966 -0.02797967 -0.03179201
   -0.02199775 -0.03596029 -0.0224496  -0.0402045

In [40]:
embedded_docs[0] # here to understand clearly , we take first indexes sentences

array([   0,    0,    0,    0, 8041, 8904, 8698, 8958])

In [42]:
print(model.predict(embedded_docs)[0])
#here you see my single words into 10 dimesional  and 10 features
# here single word convert into my 10 dimesional vector
# for example this 8904 words convert into 10 dimesional is  [-0.02791396 -0.01811381  0.04219855 -0.01401313  0.01106535  0.04672335
  # -0.04907656  0.02396217 -0.01073527 -0.01459684] .
# to undertand this go to copy    

[[-0.03791308  0.02003479 -0.03470116 -0.02139171 -0.02203513 -0.01278513
  -0.00932705  0.01903306 -0.03308139  0.02439653]
 [-0.03791308  0.02003479 -0.03470116 -0.02139171 -0.02203513 -0.01278513
  -0.00932705  0.01903306 -0.03308139  0.02439653]
 [-0.03791308  0.02003479 -0.03470116 -0.02139171 -0.02203513 -0.01278513
  -0.00932705  0.01903306 -0.03308139  0.02439653]
 [-0.03791308  0.02003479 -0.03470116 -0.02139171 -0.02203513 -0.01278513
  -0.00932705  0.01903306 -0.03308139  0.02439653]
 [-0.02565583  0.00791759 -0.02996886  0.03961018 -0.01456248 -0.04630274
  -0.02392167  0.04627511 -0.01218774  0.03797766]
 [-0.02791396 -0.01811381  0.04219855 -0.01401313  0.01106535  0.04672335
  -0.04907656  0.02396217 -0.01073527 -0.01459684]
 [-0.01583047 -0.02237868 -0.00142431  0.04683676 -0.0438031   0.02135683
  -0.00830128  0.03181615 -0.00306803 -0.01186572]
 [-0.00576218  0.02043792  0.02381966 -0.02797967 -0.03179201 -0.02199775
  -0.03596029 -0.0224496  -0.04020458  0.04396253]]

In [ ]:
# in embedding layer still more things like word2vec